CREATE TABLE ft(fk int PRIMARY KEY, fs text);

CREATE TABLE pt(pk int, ps text);

INSERT INTO ft(fk,fs) VALUES (1,'one'), (2,'two');

INSERT INTO pt(pk,ps) VALUES (1,'I'), (2,'II'), (3,'III');

-- COSI CONTROLLA I VALORI E NON FA LA CHIAVE PRIMARIA
ALTER TABLE pt ADD CONSTRAINT pc FOREIGN KEY (pk) REFERENCES ft(fk);

-- COSI NON CONTROLLA I VALORI E FA LA CHIAVE PRIMARIA
ALTER TABLE pt ADD CONSTRAINT pc FOREIGN KEY (pk) REFERENCES ft(fk) NOT VALID;