IMPORT FOREIGN SCHEMA "RDAPRD" 
--LIMIT TO(CURRENT_BURNTAREASPOLY,CURRENT_FIRESEVOLUTION,EMISSIONS,EMISSIONS_FIRES,FROM2000_BURNTAREAS,FROM2009_FIRESEVOLUTION)
LIMIT TO(CURRENT_FIRESEVOLUTION,FROM2009_FIRESEVOLUTION)
FROM SERVER esposito_orcl 
INTO rdaprd;