SELECT OGR_FID ,
POINT ,
LATITUDE ,
LONGITUDE ,
BRIGHTNESS ,
SCAN ,
TRACK ,
ACQ_DATE ,
ACQ_TIME ,
SATELLITE ,
CONFIDENCE ,
VERSION ,
BRIGHT_T31 ,
FRP ,
FLAG ,
LAND_COVER  
FROM GWSPRD.HOT_SPOTS_VIIRS
WHERE rownum < 11;
--FETCH NEXT 5 ROWS ONLY;



SELECT COUNT(OGR_FID) FROM GWSPRD.HOT_SPOTS_MODIS; 

SELECT COUNT(OGR_FID) FROM GWSPRD.HOT_SPOTS_VIIRS;

SELECT * FROM GWSPRD.HOT_SPOTS_MODIS PARTITION("hs_modis_2012");

SELECT * FROM GWSPRD.HOT_SPOTS_MODIS PARTITION("hs_modis_2015");

SELECT * FROM GWSPRD.HOT_SPOTS_VIIRS PARTITION("hs_viirs_2017");

SELECT OGR_FID,
       SCAN,
       TRACK,
       ACQ_DATE,
       ACQ_TIME,
       LENGTH('ACQ_TIME') AS "Conteggio",
       CONFIDENCE
FROM GWSPRD.HOT_SPOTS_MODIS 
PARTITION("hs_modis_2012")
WHERE CONFIDENCE = 80;

SELECT OGR_FID,
       MDSYS.SD POINT,
       SCAN,
       TRACK,
       ACQ_DATE,
       ACQ_TIME,
       CONFIDENCE
FROM GWSPRD.HOT_SPOTS_MODIS 
PARTITION("hs_modis_2012")
WHERE TRIM(ACQ_TIME) = '11:50';

