--sqlplus effis/FF19may@EDEA.IES.JRC.IT/EDEA
--rlwrap sqlplus effis/FF19may@EDEA.IES.JRC.IT/EDEA

--set colsep '|'
--set linesize 167
--set pagesize 30
--set pagesize 1000

SELECT table_name, owner, tablespace_name FROM all_tables WHERE owner='FIRPRD';

SELECT id,flag,xcen, ycen FROM FIRPRD.GRID_ECMWF014 WHERE rownum <= 10;

SELECT * FROM FIRPRD.GRID_ECMWF014 WHERE rownum <= 10;
SELECT * FROM FIRPRD.RISK_ECMWF014 WHERE rownum <= 10;

    
SELECT
    id,
    country_name,
    year,
    month,
    num_of_fires,
    num_of_meas_areas,
    ba_tot_ha,
    ba_for_ha,
    ba_nof_ha,
    min_fire_size
FROM
    firprd.eu_fires_months
WHERE year BETWEEN '2011' AND '2014'
AND COUNTRY_CODE = 'DE'
ORDER BY year;

SELECT g.OGR_FID OGR_FID,
g.SHAPE SHAPE,
g.ID ID,
g.FLAG FLAG,
g.XMIN XMIN,
g.XMAX XMAX,
g.YMIN YMIN,
g.YMAX YMAX,
g.XCEN XCEN,
g.YCEN YCEN,
g.RECT RECT,
g.CENTROID CENTROID 
FROM FIRPRD.GRID_ECMWF014 g, FIRPRD.RISK_MF010 r 
WHERE g.ID = r.ID 
AND r.ID = 344264
AND r.DAY BETWEEN 
    TO_DATE('01-JAN-2015', 'DD-MON-RR') AND TO_DATE('10-JAN-2015', 'DD-MON-RR');
    
SELECT OGR_FID ,
SHAPE ,
ID ,
FLAG 
FROM FIRPRD.GRID_ECMWF014 WHERE rownum <= 10;
    
SELECT g.OGR_FID ArcGIS_id,
g.ID ID,
g.FLAG FLAG,
MDSYS.SDO_UTIL.TO_WKTGEOMETRY(g.RECT) "Bounding Box",
MDSYS.SDO_UTIL.TO_WKTGEOMETRY(g.CENTROID) "Centroid",
r.ID0 ID0,
r.ID ID_0,
r.DAY DAY,
r.FORECAST FORECAST,
r.FWI FWI,
r.CLASSFWI "Class FWI",
r.FFMC FFMC,
r.DMC DMC,
r.DC DC,
r.ISI ISI,
r.BUI BUI,
r.DSR DSR,
r.ANOMALY ANOMALY,
r.RANKING RANKING 
FROM FIRPRD.GRID_ECMWF014 g, FIRPRD.RISK_ECMWF014 r 
WHERE g.ID = r.ID 
AND r.ID = 344264
AND r.DAY BETWEEN 
    TO_DATE('01-JAN-2015', 'DD-MON-RR') AND TO_DATE('10-JAN-2015', 'DD-MON-RR');
    
SELECT  r.DAY,g.OGR_FID, r.FWI,
        SDO_UTIL.TO_WKTGEOMETRY(SDO_GEOM.SDO_CENTROID(g.SHAPE,0.001)) "Centroid OnTheFly",
        SDO_UTIL.TO_WKTGEOMETRY(g.CENTROID) "Centroid Pre-Calculated",
        SDO_UTIL.TO_WKTGEOMETRY(g.SHAPE) WKT, 
        SDO_UTIL.TO_WKBGEOMETRY(g.SHAPE) WKB,
        SDO_UTIL.TO_KMLGEOMETRY(g.SHAPE) KML,
        SDO_UTIL.TO_GMLGEOMETRY(g.SHAPE) GML
FROM FIRPRD.GRID_ECMWF014 g, FIRPRD.RISK_ECMWF014 r 
WHERE g.ID = r.ID 
AND r.ID = 344264
AND r.DAY BETWEEN 
   TO_DATE('01-JAN-2015', 'DD-MON-RR') AND TO_DATE('10-JAN-2015', 'DD-MON-RR');

SELECT  r.DAY,g.OGR_FID, r.FWI,
        SDO_UTIL.TO_WKTGEOMETRY(SDO_GEOM.SDO_CENTROID(g.SHAPE,0.001)) "Centroid OnTheFly",
        SDO_UTIL.TO_WKTGEOMETRY(g.CENTROID) "Centroid Pre-Calculated"      
FROM FIRPRD.GRID_ECMWF014 g, FIRPRD.RISK_ECMWF014 r 
WHERE g.ID = r.ID 
AND r.ID = 344264
AND r.DAY BETWEEN 
   TO_DATE('01-JAN-2015', 'DD-MON-RR') AND TO_DATE('10-JAN-2015', 'DD-MON-RR');
   
SELECT  g.OGR_FID,
        SDO_UTIL.TO_WKTGEOMETRY(SDO_GEOM.SDO_CENTROID(g.SHAPE,0.001)) "Centroid OnTheFly",
        SDO_UTIL.TO_WKTGEOMETRY(g.CENTROID) "Centroid Pre-Calculated"      
FROM FIRPRD.GRID_ECMWF014 g;