DROP SERVER IF EXISTS esposito_orcl CASCADE;

SELECT oracle_diag();

CREATE SERVER esposito_orcl FOREIGN DATA WRAPPER oracle_fdw 
	OPTIONS(dbserver '//esposito.ies.jrc.org/esposito')

GRANT USAGE ON FOREIGN SERVER esposito_orcl TO e1gwis_test;

CREATE USER MAPPING FOR e1gwis_test SERVER esposito_orcl 
	OPTIONS (user 'effis', password 'FF19may');

CREATE SCHEMA IF NOT EXISTS rdaprd1;

IMPORT FOREIGN SCHEMA "RDAPRD" 
LIMIT TO(CURRENT_BURNTAREASPOLY,CURRENT_FIRESEVOLUTION,EMISSIONS,EMISSIONS_FIRES,FROM2000_BURNTAREAS,FROM2009_FIRESEVOLUTION)
FROM SERVER esposito_orcl 
INTO rdaprd1;